
spring:
  datasource:
    url:    jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username:   root
    password:   root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: catalog-service
  main:
    allow-bean-definition-overriding: true